apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  generation: 1
  name: businessautomation-operator
  selfLink: /apis/operators.coreos.com/v1alpha1/namespaces/rhpam75-operator-lab-user1/subscriptions/businessautomation-operator
spec:
  channel: stable
  installPlanApproval: Automatic
  name: businessautomation-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: businessautomation-operator.1.2.0
